package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String mainWebsite;
     private String supportWebsite;
     private Byte active;
     private Set products = new HashSet(0);

    public Brand() {
    }

    public Brand(String name, String mainWebsite, String supportWebsite, Byte active, Set products) {
       this.name = name;
       this.mainWebsite = mainWebsite;
       this.supportWebsite = supportWebsite;
       this.active = active;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMainWebsite() {
        return this.mainWebsite;
    }
    
    public void setMainWebsite(String mainWebsite) {
        this.mainWebsite = mainWebsite;
    }
    public String getSupportWebsite() {
        return this.supportWebsite;
    }
    
    public void setSupportWebsite(String supportWebsite) {
        this.supportWebsite = supportWebsite;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


