package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Byte active;
     private Set specs = new HashSet(0);
     private Set products = new HashSet(0);

    public Category() {
    }

    public Category(String name, Byte active, Set specs, Set products) {
       this.name = name;
       this.active = active;
       this.specs = specs;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getSpecs() {
        return this.specs;
    }
    
    public void setSpecs(Set specs) {
        this.specs = specs;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


