package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer id;
     private District district;
     private String name;
     private String postcode;
     private Set invoices = new HashSet(0);
     private Set shippingAddresses = new HashSet(0);

    public City() {
    }

	
    public City(District district) {
        this.district = district;
    }
    public City(District district, String name, String postcode, Set invoices, Set shippingAddresses) {
       this.district = district;
       this.name = name;
       this.postcode = postcode;
       this.invoices = invoices;
       this.shippingAddresses = shippingAddresses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getShippingAddresses() {
        return this.shippingAddresses;
    }
    
    public void setShippingAddresses(Set shippingAddresses) {
        this.shippingAddresses = shippingAddresses;
    }




}


