package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String fname;
     private String lname;
     private String mobile;
     private String email;
     private String image;
     private String password;
     private Date createdOn;
     private String fcmToken;
     private transient Set wishlists = new HashSet(0);
     private transient Set shippingAddresses = new HashSet(0);
     private transient Set invoices = new HashSet(0);
     private transient Set productReviews = new HashSet(0);
     private transient Set carts = new HashSet(0);

    public Customer() {
    }

    public Customer(String username, String fname, String lname, String mobile, String email, String image, String password, Date createdOn, String fcmToken, Set wishlists, Set shippingAddresses, Set invoices, Set productReviews, Set carts) {
       this.username = username;
       this.fname = fname;
       this.lname = lname;
       this.mobile = mobile;
       this.email = email;
       this.image = image;
       this.password = password;
       this.createdOn = createdOn;
       this.fcmToken = fcmToken;
       this.wishlists = wishlists;
       this.shippingAddresses = shippingAddresses;
       this.invoices = invoices;
       this.productReviews = productReviews;
       this.carts = carts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getFcmToken() {
        return this.fcmToken;
    }
    
    public void setFcmToken(String fcmToken) {
        this.fcmToken = fcmToken;
    }
    public Set getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set wishlists) {
        this.wishlists = wishlists;
    }
    public Set getShippingAddresses() {
        return this.shippingAddresses;
    }
    
    public void setShippingAddresses(Set shippingAddresses) {
        this.shippingAddresses = shippingAddresses;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getProductReviews() {
        return this.productReviews;
    }
    
    public void setProductReviews(Set productReviews) {
        this.productReviews = productReviews;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


