package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
public class District  implements java.io.Serializable {


     private Integer id;
     private Province province;
     private String name;
     private Double deliveryFee;
     private Byte active;
     private Set shippingAddresses = new HashSet(0);
     private Set cities = new HashSet(0);

    public District() {
    }

	
    public District(Province province) {
        this.province = province;
    }
    public District(Province province, String name, Double deliveryFee, Byte active, Set shippingAddresses, Set cities) {
       this.province = province;
       this.name = name;
       this.deliveryFee = deliveryFee;
       this.active = active;
       this.shippingAddresses = shippingAddresses;
       this.cities = cities;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getDeliveryFee() {
        return this.deliveryFee;
    }
    
    public void setDeliveryFee(Double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public Set getShippingAddresses() {
        return this.shippingAddresses;
    }
    
    public void setShippingAddresses(Set shippingAddresses) {
        this.shippingAddresses = shippingAddresses;
    }
    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }




}


