package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * InvoiceItemId generated by hbm2java
 */
public class InvoiceItemId  implements java.io.Serializable {


     private int invoiceId;
     private int stockId;

    public InvoiceItemId() {
    }

    public InvoiceItemId(int invoiceId, int stockId) {
       this.invoiceId = invoiceId;
       this.stockId = stockId;
    }
   
    public int getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(int invoiceId) {
        this.invoiceId = invoiceId;
    }
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoiceItemId) ) return false;
		 InvoiceItemId castOther = ( InvoiceItemId ) other; 
         
		 return (this.getInvoiceId()==castOther.getInvoiceId())
 && (this.getStockId()==castOther.getStockId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInvoiceId();
         result = 37 * result + this.getStockId();
         return result;
   }   


}


