package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private InvoiceItemId id;
     private Invoice invoice;
     private Stock stock;
     private Double discount;
     private Integer qty;

    public InvoiceItem() {
    }

	
    public InvoiceItem(InvoiceItemId id, Invoice invoice, Stock stock) {
        this.id = id;
        this.invoice = invoice;
        this.stock = stock;
    }
    public InvoiceItem(InvoiceItemId id, Invoice invoice, Stock stock, Double discount, Integer qty) {
       this.id = id;
       this.invoice = invoice;
       this.stock = stock;
       this.discount = discount;
       this.qty = qty;
    }
   
    public InvoiceItemId getId() {
        return this.id;
    }
    
    public void setId(InvoiceItemId id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


