package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private City city;
     private Customer customer;
     private Byte deliveryMethod;
     private Double delFee;
     private String address;
     private String billingAddress;
     private Integer billingCityId;
     private Date createdOn;
     private Date lastChangedOn;
     private Byte orderStatus;
     private Set invoiceItems = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(City city, Customer customer) {
        this.city = city;
        this.customer = customer;
    }
    public Invoice(City city, Customer customer, Byte deliveryMethod, Double delFee, String address, String billingAddress, Integer billingCityId, Date createdOn, Date lastChangedOn, Byte orderStatus, Set invoiceItems) {
       this.city = city;
       this.customer = customer;
       this.deliveryMethod = deliveryMethod;
       this.delFee = delFee;
       this.address = address;
       this.billingAddress = billingAddress;
       this.billingCityId = billingCityId;
       this.createdOn = createdOn;
       this.lastChangedOn = lastChangedOn;
       this.orderStatus = orderStatus;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Byte getDeliveryMethod() {
        return this.deliveryMethod;
    }
    
    public void setDeliveryMethod(Byte deliveryMethod) {
        this.deliveryMethod = deliveryMethod;
    }
    public Double getDelFee() {
        return this.delFee;
    }
    
    public void setDelFee(Double delFee) {
        this.delFee = delFee;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBillingAddress() {
        return this.billingAddress;
    }
    
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }
    public Integer getBillingCityId() {
        return this.billingCityId;
    }
    
    public void setBillingCityId(Integer billingCityId) {
        this.billingCityId = billingCityId;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Date getLastChangedOn() {
        return this.lastChangedOn;
    }
    
    public void setLastChangedOn(Date lastChangedOn) {
        this.lastChangedOn = lastChangedOn;
    }
    public Byte getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


