package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * ProductHasSpecId generated by hbm2java
 */
public class ProductHasSpecId  implements java.io.Serializable {


     private int productId;
     private int specId;

    public ProductHasSpecId() {
    }

    public ProductHasSpecId(int productId, int specId) {
       this.productId = productId;
       this.specId = specId;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getSpecId() {
        return this.specId;
    }
    
    public void setSpecId(int specId) {
        this.specId = specId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductHasSpecId) ) return false;
		 ProductHasSpecId castOther = ( ProductHasSpecId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getSpecId()==castOther.getSpecId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + this.getSpecId();
         return result;
   }   


}


