package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * ProductHasSpec generated by hbm2java
 */
public class ProductHasSpec  implements java.io.Serializable {


     private ProductHasSpecId id;
     private Product product;
     private Spec spec;
     private String specValue;

    public ProductHasSpec() {
    }

	
    public ProductHasSpec(ProductHasSpecId id, Product product, Spec spec) {
        this.id = id;
        this.product = product;
        this.spec = spec;
    }
    public ProductHasSpec(ProductHasSpecId id, Product product, Spec spec, String specValue) {
       this.id = id;
       this.product = product;
       this.spec = spec;
       this.specValue = specValue;
    }
   
    public ProductHasSpecId getId() {
        return this.id;
    }
    
    public void setId(ProductHasSpecId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Spec getSpec() {
        return this.spec;
    }
    
    public void setSpec(Spec spec) {
        this.spec = spec;
    }
    public String getSpecValue() {
        return this.specValue;
    }
    
    public void setSpecValue(String specValue) {
        this.specValue = specValue;
    }




}


