package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * ProductImageId generated by hbm2java
 */
public class ProductImageId  implements java.io.Serializable {


     private int productId;
     private String image;

    public ProductImageId() {
    }

    public ProductImageId(int productId, String image) {
       this.productId = productId;
       this.image = image;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductImageId) ) return false;
		 ProductImageId castOther = ( ProductImageId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && ( (this.getImage()==castOther.getImage()) || ( this.getImage()!=null && castOther.getImage()!=null && this.getImage().equals(castOther.getImage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + ( getImage() == null ? 0 : this.getImage().hashCode() );
         return result;
   }   


}


