package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Brand brand;
     private Category category;
     private String name;
     private String description;
     private Set wishlists = new HashSet(0);
     private Set productReviews = new HashSet(0);
     private Set productHasSpecs = new HashSet(0);
     private Set productImages = new HashSet(0);
     private Set stocks = new HashSet(0);

    public Product() {
    }

	
    public Product(Brand brand, Category category) {
        this.brand = brand;
        this.category = category;
    }
    public Product(Brand brand, Category category, String name, String description, Set wishlists, Set productReviews, Set productHasSpecs, Set productImages, Set stocks) {
       this.brand = brand;
       this.category = category;
       this.name = name;
       this.description = description;
       this.wishlists = wishlists;
       this.productReviews = productReviews;
       this.productHasSpecs = productHasSpecs;
       this.productImages = productImages;
       this.stocks = stocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set wishlists) {
        this.wishlists = wishlists;
    }
    public Set getProductReviews() {
        return this.productReviews;
    }
    
    public void setProductReviews(Set productReviews) {
        this.productReviews = productReviews;
    }
    public Set getProductHasSpecs() {
        return this.productHasSpecs;
    }
    
    public void setProductHasSpecs(Set productHasSpecs) {
        this.productHasSpecs = productHasSpecs;
    }
    public Set getProductImages() {
        return this.productImages;
    }
    
    public void setProductImages(Set productImages) {
        this.productImages = productImages;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


