package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * ProductReviewId generated by hbm2java
 */
public class ProductReviewId  implements java.io.Serializable {


     private int productId;
     private int customerId;

    public ProductReviewId() {
    }

    public ProductReviewId(int productId, int customerId) {
       this.productId = productId;
       this.customerId = customerId;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductReviewId) ) return false;
		 ProductReviewId castOther = ( ProductReviewId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getCustomerId()==castOther.getCustomerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + this.getCustomerId();
         return result;
   }   


}


