package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {


     private ProductImageId id;
     private Product product;

    public ProductImage() {
    }

    public ProductImage(ProductImageId id, Product product) {
       this.id = id;
       this.product = product;
    }
   
    public ProductImageId getId() {
        return this.id;
    }
    
    public void setId(ProductImageId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


