package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ShippingAddress generated by hbm2java
 */
public class ShippingAddress  implements java.io.Serializable {


     private Integer id;
     private City city;
     private District district;
     private Province province;
     private String name;
     private Set customers = new HashSet(0);

    public ShippingAddress() {
    }

	
    public ShippingAddress(City city, District district, Province province) {
        this.city = city;
        this.district = district;
        this.province = province;
    }
    public ShippingAddress(City city, District district, Province province, String name, Set customers) {
       this.city = city;
       this.district = district;
       this.province = province;
       this.name = name;
       this.customers = customers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


