package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private transient UserType userType;
     private String username;
     private String password;
     private Byte active;
     private String fcmToken;

    public User() {
    }

	
    public User(UserType userType) {
        this.userType = userType;
    }
    public User(UserType userType, String username, String password, Byte active, String fcmToken) {
       this.userType = userType;
       this.username = username;
       this.password = password;
       this.active = active;
       this.fcmToken = fcmToken;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public String getFcmToken() {
        return this.fcmToken;
    }
    
    public void setFcmToken(String fcmToken) {
        this.fcmToken = fcmToken;
    }




}


