package hibernate;
// Generated Mar 10, 2021 4:50:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userPrivileges = new HashSet(0);
     private Set users = new HashSet(0);

    public UserType() {
    }

    public UserType(String name, Set userPrivileges, Set users) {
       this.name = name;
       this.userPrivileges = userPrivileges;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserPrivileges() {
        return this.userPrivileges;
    }
    
    public void setUserPrivileges(Set userPrivileges) {
        this.userPrivileges = userPrivileges;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


