apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtek
spec:
  selector:
    matchLabels:
      app: microtek
  replicas: 1
  template:
    metadata:
      labels:
        app: microtek
    spec:
      containers:
        - name: microtek-db
          image: lakshannv/microtek-db:demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
        - name: microtek
          image: lakshannv/microtek:1.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /opt/payara/appserver/glassfish/domains/domain1/applications/microtek/assets/img
      volumes:
        - name: data
          hostPath:
            path: /shared/microtek
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: microtek
spec:
  selector:
    app: microtek
  ports:
    - protocol: "TCP"
      port: 8282
      nodePort: 32500
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: microtek-payara-server
spec:
  selector:
    app: microtek
  ports:
    - protocol: "TCP"
      port: 8283
      nodePort: 32501
      targetPort: 4848
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: microtek-db
spec:
  selector:
    app: microtek
  ports:
    - protocol: "TCP"
      port: 8280
      nodePort: 32450
      targetPort: 3306
  type: NodePort