apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtek
spec:
  selector:
    matchLabels:
      app: microtek
  replicas: 1
  template:
    metadata:
      labels:
        app: microtek
    spec:
      containers:
        - name: microtek
          image: lakshannv/microtek:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: microtek
spec:
  selector:
    app: microtek
  ports:
    - protocol: "TCP"
      port: 8282
      nodePort: 32500
      targetPort: 8080
  type: NodePort
